name: tree_force
description: A web ui framework based on a widget tree inspired by Flutter.
version: 0.2.1
author: Oliver Damm <oliver.damm@gmx.de>
homepage: https://www.github.com/blimster/widget_tree

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  vector_math: ^2.0.8
  redux: ^3.0.0

dev_dependencies:
  build_runner: ^0.9.1
  build_web_compilers: ^0.4.0
